# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13a129226896f71c4b41309fa119c78a2bfec6a28b1fc426250cfb267b8edd38edefd49c3fef45fe92e3f3ab6163271807081e12d3d0dd8386ca4074ee549713

test:
  secret_key_base: 01fedc60d310dfd96bbc77f725a7f2664e36a35f1f51ca0f936b4909c9600d05e9e2f5d851ad2a46e18b2634e854c8cf474b350b6c198df38a9b6425d9c09a7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
